use crate::models::{Kana, KanaCategory, KanaType};

struct RawKana {
    character: &'static str,
    romaji: &'static [&'static str],
    category: KanaCategory,
    kana_type: KanaType,
}

const RAW_HIRAGANA: &[RawKana] = &[
    RawKana { character: "あ", romaji: &["a"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "い", romaji: &["i"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "う", romaji: &["u"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "え", romaji: &["e"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "お", romaji: &["o"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "か", romaji: &["ka"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "き", romaji: &["ki"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "く", romaji: &["ku"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "け", romaji: &["ke"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "こ", romaji: &["ko"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "さ", romaji: &["sa"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "し", romaji: &["shi", "si"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "す", romaji: &["su"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "せ", romaji: &["se"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "そ", romaji: &["so"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "た", romaji: &["ta"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ち", romaji: &["chi", "ti"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "つ", romaji: &["tsu", "tu"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "て", romaji: &["te"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "と", romaji: &["to"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "な", romaji: &["na"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "に", romaji: &["ni"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ぬ", romaji: &["nu"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ね", romaji: &["ne"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "の", romaji: &["no"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "は", romaji: &["ha"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ひ", romaji: &["hi"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ふ", romaji: &["fu", "hu"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "へ", romaji: &["he"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ほ", romaji: &["ho"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ま", romaji: &["ma"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "み", romaji: &["mi"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "む", romaji: &["mu"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "め", romaji: &["me"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "も", romaji: &["mo"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "や", romaji: &["ya"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ゆ", romaji: &["yu"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "よ", romaji: &["yo"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ら", romaji: &["ra"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "り", romaji: &["ri"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "る", romaji: &["ru"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "れ", romaji: &["re"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ろ", romaji: &["ro"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "わ", romaji: &["wa"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "を", romaji: &["wo"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "ん", romaji: &["n"], category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    RawKana { character: "が", romaji: &["ga"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぎ", romaji: &["gi"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぐ", romaji: &["gu"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "げ", romaji: &["ge"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ご", romaji: &["go"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ざ", romaji: &["za"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "じ", romaji: &["ji", "zi"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ず", romaji: &["zu"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぜ", romaji: &["ze"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぞ", romaji: &["zo"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "だ", romaji: &["da"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぢ", romaji: &["ji", "zi"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "づ", romaji: &["zu"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "で", romaji: &["de"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ど", romaji: &["do"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ば", romaji: &["ba"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "び", romaji: &["bi"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぶ", romaji: &["bu"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "べ", romaji: &["be"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぼ", romaji: &["bo"], category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    RawKana { character: "ぱ", romaji: &["pa"], category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    RawKana { character: "ぴ", romaji: &["pi"], category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    RawKana { character: "ぷ", romaji: &["pu"], category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    RawKana { character: "ぺ", romaji: &["pe"], category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    RawKana { character: "ぽ", romaji: &["po"], category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    RawKana { character: "きゃ", romaji: &["kya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "きゅ", romaji: &["kyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "きょ", romaji: &["kyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "しゃ", romaji: &["sha", "sya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "しゅ", romaji: &["shu", "syu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "しょ", romaji: &["sho", "syo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ちゃ", romaji: &["cha", "tya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ちゅ", romaji: &["chu", "tyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ちょ", romaji: &["cho", "tyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "にゃ", romaji: &["nya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "にゅ", romaji: &["nyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "にょ", romaji: &["nyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ひゃ", romaji: &["hya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ひゅ", romaji: &["hyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ひょ", romaji: &["hyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "みゃ", romaji: &["mya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "みゅ", romaji: &["myu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "みょ", romaji: &["myo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "りゃ", romaji: &["rya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "りゅ", romaji: &["ryu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "りょ", romaji: &["ryo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ぎゃ", romaji: &["gya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ぎゅ", romaji: &["gyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ぎょ", romaji: &["gyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "じゃ", romaji: &["ja", "zya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "じゅ", romaji: &["ju", "zyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "じょ", romaji: &["jo", "zyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "びゃ", romaji: &["bya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "びゅ", romaji: &["byu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "びょ", romaji: &["byo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ぴゃ", romaji: &["pya"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ぴゅ", romaji: &["pyu"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    RawKana { character: "ぴょ", romaji: &["pyo"], category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
];

const RAW_KATAKANA: &[RawKana] = &[
    RawKana { character: "ア", romaji: &["a"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "イ", romaji: &["i"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ウ", romaji: &["u"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "エ", romaji: &["e"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "オ", romaji: &["o"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "カ", romaji: &["ka"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "キ", romaji: &["ki"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ク", romaji: &["ku"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ケ", romaji: &["ke"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "コ", romaji: &["ko"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "サ", romaji: &["sa"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "シ", romaji: &["shi", "si"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ス", romaji: &["su"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "セ", romaji: &["se"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ソ", romaji: &["so"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "タ", romaji: &["ta"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "チ", romaji: &["chi", "ti"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ツ", romaji: &["tsu", "tu"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "テ", romaji: &["te"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ト", romaji: &["to"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ナ", romaji: &["na"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ニ", romaji: &["ni"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ヌ", romaji: &["nu"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ネ", romaji: &["ne"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ノ", romaji: &["no"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ハ", romaji: &["ha"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ヒ", romaji: &["hi"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "フ", romaji: &["fu", "hu"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ヘ", romaji: &["he"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ホ", romaji: &["ho"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "マ", romaji: &["ma"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ミ", romaji: &["mi"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ム", romaji: &["mu"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "メ", romaji: &["me"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "モ", romaji: &["mo"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ヤ", romaji: &["ya"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ユ", romaji: &["yu"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ヨ", romaji: &["yo"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ラ", romaji: &["ra"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "リ", romaji: &["ri"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ル", romaji: &["ru"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "レ", romaji: &["re"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ロ", romaji: &["ro"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ワ", romaji: &["wa"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ヲ", romaji: &["wo"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ン", romaji: &["n"], category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    RawKana { character: "ガ", romaji: &["ga"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ギ", romaji: &["gi"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "グ", romaji: &["gu"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ゲ", romaji: &["ge"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ゴ", romaji: &["go"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ザ", romaji: &["za"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ジ", romaji: &["ji", "zi"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ズ", romaji: &["zu"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ゼ", romaji: &["ze"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ゾ", romaji: &["zo"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ダ", romaji: &["da"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ヂ", romaji: &["ji", "zi"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ヅ", romaji: &["zu"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "デ", romaji: &["de"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ド", romaji: &["do"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "バ", romaji: &["ba"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ビ", romaji: &["bi"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ブ", romaji: &["bu"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ベ", romaji: &["be"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "ボ", romaji: &["bo"], category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    RawKana { character: "パ", romaji: &["pa"], category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    RawKana { character: "ピ", romaji: &["pi"], category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    RawKana { character: "プ", romaji: &["pu"], category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    RawKana { character: "ペ", romaji: &["pe"], category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    RawKana { character: "ポ", romaji: &["po"], category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    RawKana { character: "キャ", romaji: &["kya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "キュ", romaji: &["kyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "キョ", romaji: &["kyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "シャ", romaji: &["sha", "sya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "シュ", romaji: &["shu", "syu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ショ", romaji: &["sho", "syo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "チャ", romaji: &["cha", "tya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "チュ", romaji: &["chu", "tyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "チョ", romaji: &["cho", "tyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ニャ", romaji: &["nya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ニュ", romaji: &["nyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ニョ", romaji: &["nyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ヒャ", romaji: &["hya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ヒュ", romaji: &["hyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ヒョ", romaji: &["hyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ミャ", romaji: &["mya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ミュ", romaji: &["myu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ミョ", romaji: &["myo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "リャ", romaji: &["rya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "リュ", romaji: &["ryu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "リョ", romaji: &["ryo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ギャ", romaji: &["gya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ギュ", romaji: &["gyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ギョ", romaji: &["gyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ジャ", romaji: &["ja", "zya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ジュ", romaji: &["ju", "zyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ジョ", romaji: &["jo", "zyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ビャ", romaji: &["bya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ビュ", romaji: &["byu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ビョ", romaji: &["byo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ピャ", romaji: &["pya"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ピュ", romaji: &["pyu"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    RawKana { character: "ピョ", romaji: &["pyo"], category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
];

pub fn get_hiragana() -> Vec<Kana> {
    RAW_HIRAGANA.iter().map(|r| Kana {
        character: r.character.to_string(),
        romaji: r.romaji.iter().map(|&s| s.to_string()).collect(),
        category: r.category,
        kana_type: r.kana_type,
    }).collect()
}

pub fn get_katakana() -> Vec<Kana> {
    RAW_KATAKANA.iter().map(|r| Kana {
        character: r.character.to_string(),
        romaji: r.romaji.iter().map(|&s| s.to_string()).collect(),
        category: r.category,
        kana_type: r.kana_type,
    }).collect()
}

pub enum KanaSet {
    Hiragana,
    Katakana,
    Mixed,
}

impl KanaSet {
    pub fn get_data(&self) -> Vec<Kana> {
        match self {
            KanaSet::Hiragana => get_hiragana(),
            KanaSet::Katakana => get_katakana(),
            KanaSet::Mixed => [get_hiragana(), get_katakana()].concat(),
        }
    }
}
