use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KanaCategory {
    Hiragana,
    Katakana,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KanaType {
    Seion,
    Dakuon,
    Handakuon,
    Yoon,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Kana {
    pub character: &'static str,
    pub romaji: &'static str,
    pub category: KanaCategory,
    pub kana_type: KanaType,
}

pub const HIRAGANA: &[Kana] = &[
    Kana { character: "あ", romaji: "a", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "い", romaji: "i", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "う", romaji: "u", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "え", romaji: "e", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "お", romaji: "o", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "か", romaji: "ka", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "き", romaji: "ki", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "く", romaji: "ku", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "け", romaji: "ke", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "こ", romaji: "ko", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "さ", romaji: "sa", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "し", romaji: "shi", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "す", romaji: "su", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "せ", romaji: "se", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "そ", romaji: "so", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "た", romaji: "ta", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ち", romaji: "chi", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "つ", romaji: "tsu", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "て", romaji: "te", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "と", romaji: "to", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "な", romaji: "na", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "に", romaji: "ni", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ぬ", romaji: "nu", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ね", romaji: "ne", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "の", romaji: "no", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "は", romaji: "ha", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ひ", romaji: "hi", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ふ", romaji: "fu", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "へ", romaji: "he", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ほ", romaji: "ho", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ま", romaji: "ma", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "み", romaji: "mi", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "む", romaji: "mu", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "め", romaji: "me", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "も", romaji: "mo", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "や", romaji: "ya", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ゆ", romaji: "yu", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "よ", romaji: "yo", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ら", romaji: "ra", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "り", romaji: "ri", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "る", romaji: "ru", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "れ", romaji: "re", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ろ", romaji: "ro", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "わ", romaji: "wa", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "を", romaji: "wo", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "ん", romaji: "n", category: KanaCategory::Hiragana, kana_type: KanaType::Seion },
    Kana { character: "が", romaji: "ga", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぎ", romaji: "gi", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぐ", romaji: "gu", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "げ", romaji: "ge", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ご", romaji: "go", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ざ", romaji: "za", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "じ", romaji: "ji", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ず", romaji: "zu", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぜ", romaji: "ze", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぞ", romaji: "zo", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "だ", romaji: "da", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぢ", romaji: "ji", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "づ", romaji: "zu", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "で", romaji: "de", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ど", romaji: "do", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ば", romaji: "ba", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "び", romaji: "bi", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぶ", romaji: "bu", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "べ", romaji: "be", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぼ", romaji: "bo", category: KanaCategory::Hiragana, kana_type: KanaType::Dakuon },
    Kana { character: "ぱ", romaji: "pa", category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    Kana { character: "ぴ", romaji: "pi", category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    Kana { character: "ぷ", romaji: "pu", category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    Kana { character: "ぺ", romaji: "pe", category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    Kana { character: "ぽ", romaji: "po", category: KanaCategory::Hiragana, kana_type: KanaType::Handakuon },
    Kana { character: "きゃ", romaji: "kya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "きゅ", romaji: "kyu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "きょ", romaji: "kyo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "しゃ", romaji: "sha", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "しゅ", romaji: "shu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "しょ", romaji: "sho", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ちゃ", romaji: "cha", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ちゅ", romaji: "chu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ちょ", romaji: "cho", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "にゃ", romaji: "nya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "にゅ", romaji: "nyu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "にょ", romaji: "nyo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ひゃ", romaji: "hya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ひゅ", romaji: "hyu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ひょ", romaji: "hyo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "みゃ", romaji: "mya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "みゅ", romaji: "myu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "みょ", romaji: "myo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "りゃ", romaji: "rya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "りゅ", romaji: "ryu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "りょ", romaji: "ryo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ぎゃ", romaji: "gya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ぎゅ", romaji: "gyu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ぎょ", romaji: "gyo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "じゃ", romaji: "ja", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "じゅ", romaji: "ju", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "じょ", romaji: "jo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "びゃ", romaji: "bya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "びゅ", romaji: "byu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "びょ", romaji: "byo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ぴゃ", romaji: "pya", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ぴゅ", romaji: "pyu", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
    Kana { character: "ぴょ", romaji: "pyo", category: KanaCategory::Hiragana, kana_type: KanaType::Yoon },
];

pub const KATAKANA: &[Kana] = &[
    Kana { character: "ア", romaji: "a", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "イ", romaji: "i", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ウ", romaji: "u", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "エ", romaji: "e", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "オ", romaji: "o", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "カ", romaji: "ka", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "キ", romaji: "ki", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ク", romaji: "ku", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ケ", romaji: "ke", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "コ", romaji: "ko", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "サ", romaji: "sa", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "シ", romaji: "shi", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ス", romaji: "su", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "セ", romaji: "se", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ソ", romaji: "so", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "タ", romaji: "ta", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "チ", romaji: "chi", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ツ", romaji: "tsu", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "テ", romaji: "te", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ト", romaji: "to", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ナ", romaji: "na", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ニ", romaji: "ni", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ヌ", romaji: "nu", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ネ", romaji: "ne", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ノ", romaji: "no", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ハ", romaji: "ha", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ヒ", romaji: "hi", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "フ", romaji: "fu", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ヘ", romaji: "he", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ホ", romaji: "ho", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "マ", romaji: "ma", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ミ", romaji: "mi", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ム", romaji: "mu", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "メ", romaji: "me", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "モ", romaji: "mo", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ヤ", romaji: "ya", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ユ", romaji: "yu", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ヨ", romaji: "yo", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ラ", romaji: "ra", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "リ", romaji: "ri", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ル", romaji: "ru", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "レ", romaji: "re", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ロ", romaji: "ro", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ワ", romaji: "wa", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ヲ", romaji: "wo", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ン", romaji: "n", category: KanaCategory::Katakana, kana_type: KanaType::Seion },
    Kana { character: "ガ", romaji: "ga", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ギ", romaji: "gi", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "グ", romaji: "gu", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ゲ", romaji: "ge", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ゴ", romaji: "go", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ザ", romaji: "za", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ジ", romaji: "ji", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ズ", romaji: "zu", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ゼ", romaji: "ze", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ゾ", romaji: "zo", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ダ", romaji: "da", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ヂ", romaji: "ji", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ヅ", romaji: "zu", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "デ", romaji: "de", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ド", romaji: "do", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "バ", romaji: "ba", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ビ", romaji: "bi", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ブ", romaji: "bu", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ベ", romaji: "be", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "ボ", romaji: "bo", category: KanaCategory::Katakana, kana_type: KanaType::Dakuon },
    Kana { character: "パ", romaji: "pa", category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    Kana { character: "ピ", romaji: "pi", category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    Kana { character: "プ", romaji: "pu", category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    Kana { character: "ペ", romaji: "pe", category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    Kana { character: "ポ", romaji: "po", category: KanaCategory::Katakana, kana_type: KanaType::Handakuon },
    Kana { character: "キャ", romaji: "kya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "キュ", romaji: "kyu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "キョ", romaji: "kyo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "シャ", romaji: "sha", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "シュ", romaji: "shu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ショ", romaji: "sho", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "チャ", romaji: "cha", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "チュ", romaji: "chu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "チョ", romaji: "cho", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ニャ", romaji: "nya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ニュ", romaji: "nyu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ニョ", romaji: "nyo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ヒャ", romaji: "hya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ヒュ", romaji: "hyu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ヒョ", romaji: "hyo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ミャ", romaji: "mya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ミュ", romaji: "myu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ミョ", romaji: "myo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "リャ", romaji: "rya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "リュ", romaji: "ryu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "リョ", romaji: "ryo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ギャ", romaji: "gya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ギュ", romaji: "gyu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ギョ", romaji: "gyo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ジャ", romaji: "ja", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ジュ", romaji: "ju", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ジョ", romaji: "jo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ビャ", romaji: "bya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ビュ", romaji: "byu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ビョ", romaji: "byo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ピャ", romaji: "pya", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ピュ", romaji: "pyu", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
    Kana { character: "ピョ", romaji: "pyo", category: KanaCategory::Katakana, kana_type: KanaType::Yoon },
];

pub enum KanaSet {
    Hiragana,
    Katakana,
    Mixed,
}

impl KanaSet {
    pub fn get_data(&self) -> Vec<Kana> {
        match self {
            KanaSet::Hiragana => HIRAGANA.to_vec(),
            KanaSet::Katakana => KATAKANA.to_vec(),
            KanaSet::Mixed => [HIRAGANA, KATAKANA].concat(),
        }
    }
}
