pub struct KanaPair {
    pub kana: &'static str,
    pub romaji: &'static str,
}

pub const KANA_DATA: &[KanaPair] = &[
    // --- HIRAGANA ---
    // Seion (Basic)
    KanaPair { kana: "あ", romaji: "a" },
    KanaPair { kana: "い", romaji: "i" },
    KanaPair { kana: "う", romaji: "u" },
    KanaPair { kana: "え", romaji: "e" },
    KanaPair { kana: "お", romaji: "o" },
    KanaPair { kana: "か", romaji: "ka" },
    KanaPair { kana: "き", romaji: "ki" },
    KanaPair { kana: "く", romaji: "ku" },
    KanaPair { kana: "け", romaji: "ke" },
    KanaPair { kana: "こ", romaji: "ko" },
    KanaPair { kana: "さ", romaji: "sa" },
    KanaPair { kana: "し", romaji: "shi" },
    KanaPair { kana: "す", romaji: "su" },
    KanaPair { kana: "せ", romaji: "se" },
    KanaPair { kana: "そ", romaji: "so" },
    KanaPair { kana: "た", romaji: "ta" },
    KanaPair { kana: "ち", romaji: "chi" },
    KanaPair { kana: "つ", romaji: "tsu" },
    KanaPair { kana: "て", romaji: "te" },
    KanaPair { kana: "と", romaji: "to" },
    KanaPair { kana: "な", romaji: "na" },
    KanaPair { kana: "に", romaji: "ni" },
    KanaPair { kana: "ぬ", romaji: "nu" },
    KanaPair { kana: "ね", romaji: "ne" },
    KanaPair { kana: "の", romaji: "no" },
    KanaPair { kana: "は", romaji: "ha" },
    KanaPair { kana: "ひ", romaji: "hi" },
    KanaPair { kana: "ふ", romaji: "fu" },
    KanaPair { kana: "へ", romaji: "he" },
    KanaPair { kana: "ほ", romaji: "ho" },
    KanaPair { kana: "ま", romaji: "ma" },
    KanaPair { kana: "み", romaji: "mi" },
    KanaPair { kana: "む", romaji: "mu" },
    KanaPair { kana: "め", romaji: "me" },
    KanaPair { kana: "も", romaji: "mo" },
    KanaPair { kana: "や", romaji: "ya" },
    KanaPair { kana: "ゆ", romaji: "yu" },
    KanaPair { kana: "よ", romaji: "yo" },
    KanaPair { kana: "ら", romaji: "ra" },
    KanaPair { kana: "り", romaji: "ri" },
    KanaPair { kana: "る", romaji: "ru" },
    KanaPair { kana: "れ", romaji: "re" },
    KanaPair { kana: "ろ", romaji: "ro" },
    KanaPair { kana: "わ", romaji: "wa" },
    KanaPair { kana: "を", romaji: "wo" },
    KanaPair { kana: "ん", romaji: "n" },

    // Dakuon (Voiced)
    KanaPair { kana: "が", romaji: "ga" },
    KanaPair { kana: "ぎ", romaji: "gi" },
    KanaPair { kana: "ぐ", romaji: "gu" },
    KanaPair { kana: "げ", romaji: "ge" },
    KanaPair { kana: "ご", romaji: "go" },
    KanaPair { kana: "ざ", romaji: "za" },
    KanaPair { kana: "じ", romaji: "ji" },
    KanaPair { kana: "ず", romaji: "zu" },
    KanaPair { kana: "ぜ", romaji: "ze" },
    KanaPair { kana: "ぞ", romaji: "zo" },
    KanaPair { kana: "だ", romaji: "da" },
    KanaPair { kana: "ぢ", romaji: "ji" },
    KanaPair { kana: "づ", romaji: "zu" },
    KanaPair { kana: "で", romaji: "de" },
    KanaPair { kana: "ど", romaji: "do" },
    KanaPair { kana: "ば", romaji: "ba" },
    KanaPair { kana: "び", romaji: "bi" },
    KanaPair { kana: "ぶ", romaji: "bu" },
    KanaPair { kana: "べ", romaji: "be" },
    KanaPair { kana: "ぼ", romaji: "bo" },

    // Handakuon (Semi-voiced)
    KanaPair { kana: "ぱ", romaji: "pa" },
    KanaPair { kana: "ぴ", romaji: "pi" },
    KanaPair { kana: "ぷ", romaji: "pu" },
    KanaPair { kana: "ぺ", romaji: "pe" },
    KanaPair { kana: "ぽ", romaji: "po" },

    // Yoon (Combination) - Hiragana
    KanaPair { kana: "きゃ", romaji: "kya" },
    KanaPair { kana: "きゅ", romaji: "kyu" },
    KanaPair { kana: "きょ", romaji: "kyo" },
    KanaPair { kana: "しゃ", romaji: "sha" },
    KanaPair { kana: "しゅ", romaji: "shu" },
    KanaPair { kana: "しょ", romaji: "sho" },
    KanaPair { kana: "ちゃ", romaji: "cha" },
    KanaPair { kana: "ちゅ", romaji: "chu" },
    KanaPair { kana: "ちょ", romaji: "cho" },
    KanaPair { kana: "にゃ", romaji: "nya" },
    KanaPair { kana: "にゅ", romaji: "nyu" },
    KanaPair { kana: "にょ", romaji: "nyo" },
    KanaPair { kana: "ひゃ", romaji: "hya" },
    KanaPair { kana: "ひゅ", romaji: "hyu" },
    KanaPair { kana: "ひょ", romaji: "hyo" },
    KanaPair { kana: "みゃ", romaji: "mya" },
    KanaPair { kana: "みゅ", romaji: "myu" },
    KanaPair { kana: "みょ", romaji: "myo" },
    KanaPair { kana: "りゃ", romaji: "rya" },
    KanaPair { kana: "りゅ", romaji: "ryu" },
    KanaPair { kana: "りょ", romaji: "ryo" },
    KanaPair { kana: "ぎゃ", romaji: "gya" },
    KanaPair { kana: "ぎゅ", romaji: "gyu" },
    KanaPair { kana: "ぎょ", romaji: "gyo" },
    KanaPair { kana: "じゃ", romaji: "ja" },
    KanaPair { kana: "じゅ", romaji: "ju" },
    KanaPair { kana: "じょ", romaji: "jo" },
    KanaPair { kana: "びゃ", romaji: "bya" },
    KanaPair { kana: "びゅ", romaji: "byu" },
    KanaPair { kana: "びょ", romaji: "byo" },
    KanaPair { kana: "ぴゃ", romaji: "pya" },
    KanaPair { kana: "ぴゅ", romaji: "pyu" },
    KanaPair { kana: "ぴょ", romaji: "pyo" },

    // --- KATAKANA ---
    // Seion (Basic)
    KanaPair { kana: "ア", romaji: "a" },
    KanaPair { kana: "イ", romaji: "i" },
    KanaPair { kana: "ウ", romaji: "u" },
    KanaPair { kana: "エ", romaji: "e" },
    KanaPair { kana: "オ", romaji: "o" },
    KanaPair { kana: "カ", romaji: "ka" },
    KanaPair { kana: "キ", romaji: "ki" },
    KanaPair { kana: "ク", romaji: "ku" },
    KanaPair { kana: "ケ", romaji: "ke" },
    KanaPair { kana: "コ", romaji: "ko" },
    KanaPair { kana: "サ", romaji: "sa" },
    KanaPair { kana: "シ", romaji: "shi" },
    KanaPair { kana: "ス", romaji: "su" },
    KanaPair { kana: "セ", romaji: "se" },
    KanaPair { kana: "ソ", romaji: "so" },
    KanaPair { kana: "タ", romaji: "ta" },
    KanaPair { kana: "チ", romaji: "chi" },
    KanaPair { kana: "ツ", romaji: "tsu" },
    KanaPair { kana: "テ", romaji: "te" },
    KanaPair { kana: "ト", romaji: "to" },
    KanaPair { kana: "ナ", romaji: "na" },
    KanaPair { kana: "ニ", romaji: "ni" },
    KanaPair { kana: "ヌ", romaji: "nu" },
    KanaPair { kana: "ネ", romaji: "ne" },
    KanaPair { kana: "ノ", romaji: "no" },
    KanaPair { kana: "ハ", romaji: "ha" },
    KanaPair { kana: "ヒ", romaji: "hi" },
    KanaPair { kana: "フ", romaji: "fu" },
    KanaPair { kana: "ヘ", romaji: "he" },
    KanaPair { kana: "ホ", romaji: "ho" },
    KanaPair { kana: "マ", romaji: "ma" },
    KanaPair { kana: "ミ", romaji: "mi" },
    KanaPair { kana: "ム", romaji: "mu" },
    KanaPair { kana: "メ", romaji: "me" },
    KanaPair { kana: "モ", romaji: "mo" },
    KanaPair { kana: "ヤ", romaji: "ya" },
    KanaPair { kana: "ユ", romaji: "yu" },
    KanaPair { kana: "ヨ", romaji: "yo" },
    KanaPair { kana: "ラ", romaji: "ra" },
    KanaPair { kana: "リ", romaji: "ri" },
    KanaPair { kana: "ル", romaji: "ru" },
    KanaPair { kana: "レ", romaji: "re" },
    KanaPair { kana: "ロ", romaji: "ro" },
    KanaPair { kana: "ワ", romaji: "wa" },
    KanaPair { kana: "ヲ", romaji: "wo" },
    KanaPair { kana: "ン", romaji: "n" },

    // Dakuon (Voiced)
    KanaPair { kana: "ガ", romaji: "ga" },
    KanaPair { kana: "ギ", romaji: "gi" },
    KanaPair { kana: "グ", romaji: "gu" },
    KanaPair { kana: "ゲ", romaji: "ge" },
    KanaPair { kana: "ゴ", romaji: "go" },
    KanaPair { kana: "ザ", romaji: "za" },
    KanaPair { kana: "ジ", romaji: "ji" },
    KanaPair { kana: "ズ", romaji: "zu" },
    KanaPair { kana: "ゼ", romaji: "ze" },
    KanaPair { kana: "ゾ", romaji: "zo" },
    KanaPair { kana: "ダ", romaji: "da" },
    KanaPair { kana: "ヂ", romaji: "ji" },
    KanaPair { kana: "ヅ", romaji: "zu" },
    KanaPair { kana: "デ", romaji: "de" },
    KanaPair { kana: "ド", romaji: "do" },
    KanaPair { kana: "バ", romaji: "ba" },
    KanaPair { kana: "ビ", romaji: "bi" },
    KanaPair { kana: "ブ", romaji: "bu" },
    KanaPair { kana: "ベ", romaji: "be" },
    KanaPair { kana: "ボ", romaji: "bo" },

    // Handakuon (Semi-voiced)
    KanaPair { kana: "パ", romaji: "pa" },
    KanaPair { kana: "ピ", romaji: "pi" },
    KanaPair { kana: "プ", romaji: "pu" },
    KanaPair { kana: "ペ", romaji: "pe" },
    KanaPair { kana: "ポ", romaji: "po" },

    // Yoon (Combination) - Katakana
    KanaPair { kana: "キャ", romaji: "kya" },
    KanaPair { kana: "キュ", romaji: "kyu" },
    KanaPair { kana: "キョ", romaji: "kyo" },
    KanaPair { kana: "シャ", romaji: "sha" },
    KanaPair { kana: "シュ", romaji: "shu" },
    KanaPair { kana: "ショ", romaji: "sho" },
    KanaPair { kana: "チャ", romaji: "cha" },
    KanaPair { kana: "チュ", romaji: "chu" },
    KanaPair { kana: "チョ", romaji: "cho" },
    KanaPair { kana: "ニャ", romaji: "nya" },
    KanaPair { kana: "ニュ", romaji: "nyu" },
    KanaPair { kana: "ニョ", romaji: "nyo" },
    KanaPair { kana: "ヒャ", romaji: "hya" },
    KanaPair { kana: "ヒュ", romaji: "hyu" },
    KanaPair { kana: "ヒョ", romaji: "hyo" },
    KanaPair { kana: "ミャ", romaji: "mya" },
    KanaPair { kana: "ミュ", romaji: "myu" },
    KanaPair { kana: "ミョ", romaji: "myo" },
    KanaPair { kana: "リャ", romaji: "rya" },
    KanaPair { kana: "リュ", romaji: "ryu" },
    KanaPair { kana: "リョ", romaji: "ryo" },
    KanaPair { kana: "ギャ", romaji: "gya" },
    KanaPair { kana: "ギュ", romaji: "gyu" },
    KanaPair { kana: "ギョ", romaji: "gyo" },
    KanaPair { kana: "ジャ", romaji: "ja" },
    KanaPair { kana: "ジュ", romaji: "ju" },
    KanaPair { kana: "ジョ", romaji: "jo" },
    KanaPair { kana: "ビャ", romaji: "bya" },
    KanaPair { kana: "ビュ", romaji: "byu" },
    KanaPair { kana: "ビョ", romaji: "byo" },
    KanaPair { kana: "ピャ", romaji: "pya" },
    KanaPair { kana: "ピュ", romaji: "pyu" },
    KanaPair { kana: "ピョ", romaji: "pyo" },
];

// 必须添加这个函数，否则 db.rs 无法调用
pub fn get_all_kana() -> Vec<(&'static str, &'static str)> {
    KANA_DATA.iter().map(|k| (k.kana, k.romaji)).collect()
}